name: Secret Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  gitleaks:
    name: Run gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run gitleaks action
        uses: zricethezav/gitleaks-action@v2.5.0
        with:
          args: '--redact --exit-code=1 --report-path=gitleaks-report.json'
